**Atelier Numpy**

## Partie 1 : Listes Python vs tableaux NumPy

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0, 25.8

1) Créeation d'une liste Python stockant ces températures

In [3]:
temp_list = [24.5, 25.1, 26.3, 27.0, 25.8]
print("Températures enregistrées :", temp_list)

Températures enregistrées : [24.5, 25.1, 26.3, 27.0, 25.8]


2) Création d'un tableau NumPy équivalent stockant ces températures

In [32]:
# importation de la bibliothèque NumPy
import numpy as np

#tableau de températures sous forme de tableau NumPy
temp_array = np.array(temp_list)
print("Tableau NumPy des températures :", temp_array)


Tableau NumPy des températures : [24.5 25.1 26.3 27.  25.8]


3) Une multiplication par 2 sur ces deux collections

In [5]:
# multiplication par 2 sur ces deux collections de données
 
# multiplication par 2 sur la liste
result_list = temp_list * 2
print("Résultat de la multiplication par 2 sur la liste :", result_list)

# multiplication par 2 sur le tableau NumPy
result_array = temp_array * 2   
print("Résultat de la multiplication par 2 sur le tableau NumPy :", result_array)

Résultat de la multiplication par 2 sur la liste : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Résultat de la multiplication par 2 sur le tableau NumPy : [49.  50.2 52.6 54.  51.6]


4) La difference qu'on a observe 

- Sur la liste Python, l'opérateur * réalise une répétition : la liste est dupliquée et concaténée deux fois (elle passe de 5 à 10 éléments), ce qui n'a aucun sens mathématique pour des mesures physiques.
- Sur le tableau NumPy, l'opérateur * réalise une multiplication élément par élément (opération vectorisée) : chaque température est bien multipliée par 2, et la taille du tableau reste inchangée (5 éléments).
- Cette différence illustre l'intérêt majeur de NumPy pour le calcul scientifique : les opérations sont vectorisées, plus rapides et sémantiquement correctes pour des données numériques.

## Partie 2 – Création des données

1) Création d'un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [ ]:
# les mesures de temperature de 10 capteurs initie a 0 
capture_zero = np.zeros(10)
print("Mesures de température des 10 capteurs:", capture_zero)

Mesures de température des 10 capteurs : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Création d'un tableau contenant 10 valeurs égales à 1. 

In [ ]:
#Tableau contenant 10 valeur egal a 1 
capture_one = np.ones(10)
print("Mesures de température des 10 capteurs:", capture_one)

Mesures de température des 10 capteurs : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3) Création d'un tableau de 10 valeurs initialisées à 25.

In [10]:
# Tableau 10 valeur initialise a 25 
capture_25 = np.full(10, 25)
print("Mesures de température des 10 capteurs :", capture_25)

Mesures de température des 10 capteurs : [25 25 25 25 25 25 25 25 25 25]


4) Création d'une matrice identité de taille 5 × 5. 

In [11]:
#Matrice 5*5
identite = np.eye(5)
print("Matrice identité 5x5 :\n", identite)

Matrice identité 5x5 :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5) Création des 24 heures (de 0 à 23) de mesure d’une journée

In [12]:
# Les 24h de mesure d'une journée*
heures = np.arange(24)
print("Heures de la journée :", heures)

Heures de la journée : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6) Création des 10 valeurs régulièrement réparties entre 20 °C et 30 °C  

In [13]:
#  10 valeurs régulièrement réparties entre 20 °C et 30 °C  
capture_20_30 = np.linspace(20, 30, 10)
print("Mesures de température des 10 capteurs :", capture_20_30)

Mesures de température des 10 capteurs : [20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7) Création aléatoir des températures de 100 mesures, en rendant les résultats reproductibles

In [14]:
# les températures de 100 mesures, en rendant les résultats reproductibles
np.random.seed(42)
capture_100 = np.random.uniform(20, 30, 100)
print("Mesures de température des 100 capteurs :", capture_100)

Mesures de température des 100 capteurs : [23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682
 20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
 23.58465729

In [35]:
# autrement avec default_rng() suggérée par la documentation de NumPy
rng = np.random.default_rng(seed=42)
capture_100 = rng.uniform(20, 30, 100)
print("Mesures de température des 100 capteurs :", capture_100)

Mesures de température des 100 capteurs : [27.73956049 24.3887844  28.5859792  26.97368029 20.94177348 29.75622352
 27.61139702 27.86064305 21.28113633 24.50385938 23.70798024 29.26764989
 26.4386512  28.22761613 24.43414199 22.27238722 25.54584787 20.63817256
 28.27631172 26.31664399 27.5808774  23.54525968 29.70698024 28.93121121
 27.78383497 21.94638708 24.66721004 20.43803766 21.54289492 26.83048953
 27.44762156 29.67509732 23.25825358 23.70459706 24.69555811 21.89471359
 21.29921505 24.75704926 22.26909349 26.69813995 24.37151919 28.32678196
 27.00265102 23.12366641 28.32259801 28.04764357 23.87478379 22.88328104
 26.82495504 21.39752484 21.99908202 20.0736227  27.86924378 26.64850857
 27.05165379 27.80729031 24.58915776 25.68741196 21.39796998 21.14530074
 26.68402962 24.71096206 25.65236106 27.64998857 26.3471832  25.53579401
 25.59207161 23.03950098 20.30817835 24.36717389 22.14584673 24.08528644
 28.53403073 22.33939486 20.58302742 22.81383892 22.93593758 26.61916515
 25.57032

## Partie 3 – Exploration des tableaux

1) Création d'un tableau aléatoire qui représente les 24 températures d'une journée 

In [16]:
# Tableau aléatoire qui représente les 24 températures d'une journée
np.random.seed(42)
capture_24 = np.random.uniform(15, 35, 24)
print("Mesures de température des 24 capteurs :", capture_24)

Mesures de température des 24 capteurs : [22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687]


2) Détermination des propriétés suivantes du tableau 

a) nombre de dimensions

In [17]:
# nombre de dimensions du tableau
print("Nombre de dimensions du tableau capture_24 :", capture_24.ndim)

Nombre de dimensions du tableau capture_24 : 1


b) nombre de valeurs

In [18]:
# nombre de valeurs dans le tableau
print("Nombre de valeurs dans le tableau capture_24 :", capture_24.size)

Nombre de valeurs dans le tableau capture_24 : 24


c) type des données

In [19]:
# type de données du tableau
print("Type de données du tableau capture_24 :", capture_24.dtype)

Type de données du tableau capture_24 : float64


d) forme du tableau

In [20]:
# format du tableau
print("Format du tableau capture_24 :", capture_24.shape)

Format du tableau capture_24 : (24,)


## Partie 4 – Indexation et slicing

En Considérant le tableau représentant les 24 températures d'une journée : 

1) la première mesure

In [21]:
# premiere mesure de la journée
print("Première mesure de la journée :", capture_24[0])

Première mesure de la journée : 22.49080237694725


2) la dernière mesure

In [ ]:
# derniere mesure de la journee
print("Dernière mesure de la journée :", capture_24[-1])

Dernière mesure de la journée : 22.327236865873836


3) la température de 8h

In [23]:
# Temperature de 8h 
print("Température à 8h :", capture_24[8])

Température à 8h : 27.022300234864176


4) les températures de 8h à 12h

In [24]:
# temperature de 8h à 12h
print("Températures de 8h à 12h :", capture_24[8:13])

Températures de 8h à 12h : [27.02230023 29.16145156 15.41168989 34.39819704 31.64885282]


5) les températures des 6 premières heures 

In [25]:
# temperature des 6 premieres heures de la journée
print("Températures des 6 premières heures de la journée :", capture_24[:6])

Températures des 6 premières heures de la journée : [22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041]


6) les températures des heures paires

In [26]:
# temperature des heure paires de la journee
print("Températures des heures paires de la journée :", capture_24[::2])

Températures des heures paires de la journée : [22.49080238 29.63987884 18.12037281 16.16167224 27.02230023 15.41168989
 31.64885282 18.63649934 21.08484486 23.63890037 27.23705789 20.84289297]


## Partie 5 – Filtrage booléen 

En considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les 
situations inhabituelles. 

1) Affichage des températures supérieures à 30 °C 

In [27]:
#  Affichage des températures supérieures à 30 °C
print("Températures supérieures à 30 °C :", capture_24[capture_24 > 30])

Températures supérieures à 30 °C : [34.01428613 32.32352292 34.39819704 31.64885282]


2) Affichage des températures « normales » càd comprises entre 20 °C et 30 °C 

In [28]:
#Affichage des températures « normales » càd comprises entre 20 °C et 30 °C 
print("Températures « normales » :", capture_24[(capture_24 >= 20) & (capture_24 <= 30)])

Températures « normales » : [22.49080238 29.63987884 26.97316968 27.02230023 29.16145156 21.08484486
 25.49512863 23.63890037 20.8245828  27.23705789 20.84289297 22.32723687]


3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 
Déterminons anomalies, un tableau de booléen précisant les anomalies 

In [30]:
# 3) Une température supérieure à 35 °C soit considérée comme anormale. Déterminons anomalies, un tableau de booléen précisant les anomalies 
anomalies = capture_24 > 35
print("Anomalies :", anomalies)


Anomalies : [False False False False False False False False False False False False
 False False False False False False False False False False False False]


4) Déterminons le nombre de températures anormales à l’aide de la variable anomalies  

In [31]:
# Le nombre de températures anormales à l’aide de la variable anomalies  
nombre_anomalies = np.sum(anomalies)
print("Nombre de températures anormales :", nombre_anomalies)

Nombre de températures anormales : 0


## Partie 6 – Manipulation des dimension

On suppose qu’on a 5 capteurs.

1) Création aléatoirement de la matrice représentant les températures mesurées par ces capteurs durant 
une journée

In [71]:
# On suppose qu’on a 5 capteurs.
#1) Création aléatoirement de la matrice représentant les températures mesurées par ces capteurs durant 
#une journée
np.random.seed(42)
matrice_capteurs = np.random.uniform(15, 35, (5, 24))
print("Matrice des températures mesurées par les capteurs durant une journée :\n", matrice_capteurs)
print("shape de la matrice :", matrice_capteurs.shape)


Matrice des températures mesurées par les capteurs durant une journée :
 [[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
  16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
  31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
  23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687]
 [24.12139968 30.70351923 18.99347564 25.28468877 26.84829138 15.92900825
  27.15089704 18.41048247 16.30103186 33.97771075 34.31264066 31.16794696
  21.09227538 16.95344228 28.68466053 23.80304987 17.4407647  24.9035382
  15.68777042 33.18640804 20.17559963 28.25044569 21.23422152 25.40136042]
 [25.93420559 18.69708911 34.39169256 30.50265647 33.78997883 32.89654701
  26.95799958 33.4374847  16.76985004 18.91965725 15.90454578 21.50660662
  22.77354579 20.42698064 31.57475018 22.13506653 20.61869019 25.85392166
  17.8184845  31.04393962 16.49101287 34.73773873 30.44489539 18.97431363]
 [15.11044234 31.30922857 29.13714688

In [ ]:
# autre facon avec default_rng()
rng = np.random.default_rng(seed=42)
matrice_capteurs = rng.uniform(15, 35, (5, 24))
print("Matrice des températures mesurées par les capteurs durant une journée :\n", matrice_capteurs)
print("\n shape de la matrice :", matrice_capteurs.shape)

Matrice des températures mesurées par les capteurs durant une journée :
 [[30.47912097 23.7775688  32.1719584  28.94736058 16.88354696 34.51244703
  30.22279404 30.72128611 17.56227265 24.00771876 22.41596048 33.53529978
  27.8773024  31.45523227 23.86828398 19.54477444 26.09169574 16.27634512
  31.55262344 27.63328798 30.1617548  22.09051936 34.41396049 32.86242243]
 [30.56766994 18.89277416 24.33442007 15.87607532 18.08578984 28.66097906
  29.89524312 34.35019465 21.51650716 22.40919412 24.39111623 18.78942718
  17.59843011 24.51409852 19.53818698 28.39627989 23.74303838 31.65356392
  29.00530204 21.24733283 31.64519603 31.09528715 22.74956758 20.76656208]
 [28.64991008 17.79504967 18.99816405 15.1472454  30.73848755 28.29701713
  29.10330757 30.61458062 24.17831551 26.37482392 17.79593996 17.29060147
  28.36805924 24.42192412 26.30472213 30.29997715 27.6943664  26.07158801
  26.18414321 21.07900196 15.61635669 23.73434778 19.29169346 23.17057287]
 [32.06806147 19.67878972 16.1660548

2) Transformation de la matrice en un tableau unidimensionnel 

In [40]:
# Transformation la matrice en un tableau unidimensionnel 
capteurs_1d = matrice_capteurs.flatten()
print("Tableau unidimensionnel des températures :\n", capteurs_1d)

Tableau unidimensionnel des températures :
 [30.47912097 23.7775688  32.1719584  28.94736058 16.88354696 34.51244703
 30.22279404 30.72128611 17.56227265 24.00771876 22.41596048 33.53529978
 27.8773024  31.45523227 23.86828398 19.54477444 26.09169574 16.27634512
 31.55262344 27.63328798 30.1617548  22.09051936 34.41396049 32.86242243
 30.56766994 18.89277416 24.33442007 15.87607532 18.08578984 28.66097906
 29.89524312 34.35019465 21.51650716 22.40919412 24.39111623 18.78942718
 17.59843011 24.51409852 19.53818698 28.39627989 23.74303838 31.65356392
 29.00530204 21.24733283 31.64519603 31.09528715 22.74956758 20.76656208
 28.64991008 17.79504967 18.99816405 15.1472454  30.73848755 28.29701713
 29.10330757 30.61458062 24.17831551 26.37482392 17.79593996 17.29060147
 28.36805924 24.42192412 26.30472213 30.29997715 27.6943664  26.07158801
 26.18414321 21.07900196 15.61635669 23.73434778 19.29169346 23.17057287
 32.06806147 19.67878972 16.16605483 20.62767784 20.87187516 28.23833029
 26.140

3) Détermination de la transposée de la matrice

In [41]:
# La transposée de la matrice
matrice_transposee = matrice_capteurs.T
print("Matrice transposée :\n", matrice_transposee)

Matrice transposée :
 [[30.47912097 30.56766994 28.64991008 32.06806147 22.23625221]
 [23.7775688  18.89277416 17.79504967 19.67878972 16.75299839]
 [32.1719584  24.33442007 18.99816405 16.16605483 17.36011804]
 [28.94736058 15.87607532 15.1472454  20.62767784 34.23795329]
 [16.88354696 18.08578984 30.73848755 20.87187516 33.17161381]
 [34.51244703 28.66097906 28.29701713 28.23833029 28.99414268]
 [30.22279404 29.89524312 29.10330757 26.14064305 20.31739923]
 [30.72128611 34.35019465 30.61458062 30.67796418 34.38352755]
 [17.56227265 21.51650716 24.17831551 28.28627081 30.57501808]
 [24.00771876 22.40919412 26.37482392 23.12773723 29.33780378]
 [22.41596048 24.39111623 17.79593996 31.28040769 23.98723004]
 [33.53529978 18.78942718 17.29060147 18.3394584  20.44483124]
 [27.8773024  17.59843011 28.36805924 15.45424146 16.92781924]
 [31.45523227 24.51409852 24.42192412 16.80095722 33.05204793]
 [23.86828398 19.53818698 26.30472213 29.44718701 24.1155258 ]
 [19.54477444 28.39627989 30.2999

4) Extraction de toutes les mesures du capteur 1

In [45]:
# Toutes les mesures du capteur 1
mesures_capteur_1 = matrice_capteurs[0, :]
print("Mesures du capteur 1 :\n", mesures_capteur_1)

Mesures du capteur 1 :
 [30.47912097 23.7775688  32.1719584  28.94736058 16.88354696 34.51244703
 30.22279404 30.72128611 17.56227265 24.00771876 22.41596048 33.53529978
 27.8773024  31.45523227 23.86828398 19.54477444 26.09169574 16.27634512
 31.55262344 27.63328798 30.1617548  22.09051936 34.41396049 32.86242243]


5) Extraction de toutes les mesures du capteur 5

In [46]:
# Toutes les mesures du capteur 5
mesures_capteur_5 = matrice_capteurs[4, :]
print("Mesures du capteur 5 :\n", mesures_capteur_5)

Mesures du capteur 5 :
 [22.23625221 16.75299839 17.36011804 34.23795329 33.17161381 28.99414268
 20.31739923 34.38352755 30.57501808 29.33780378 23.98723004 20.44483124
 16.92781924 33.05204793 24.1155258  19.0472673  21.11913248 26.58439138
 18.53545566 32.13228568 30.1703906  29.38925912 23.6418608  27.54617681]


6) Extraction des mesures de tous les capteurs à 10h 

In [47]:
# Les mesures de tous les capteurs à 10h 
mesures_10h = matrice_capteurs[:, 9]  # 10h correspond à l'indice 9
print("Mesures de tous les capteurs à 10h :\n", mesures_10h)

Mesures de tous les capteurs à 10h :
 [24.00771876 22.40919412 26.37482392 23.12773723 29.33780378]


7) Extraction des mesures des capteurs 2 à 4 entre 8h et 12h

In [48]:
# Les mesures des capteurs 2 à 4 entre 8h et 12h
mesures_capteurs_2_a_4 = matrice_capteurs[1:4, 7:12]  # Indices des capteurs 2 à 4 et des heures 8h à 12h
print("Mesures des capteurs 2 à 4 entre 8h et 12h :\n", mesures_capteurs_2_a_4)

Mesures des capteurs 2 à 4 entre 8h et 12h :
 [[34.35019465 21.51650716 22.40919412 24.39111623 18.78942718]
 [30.61458062 24.17831551 26.37482392 17.79593996 17.29060147]
 [30.67796418 28.28627081 23.12773723 31.28040769 18.3394584 ]]


## Partie 7 – Concaténation

On suppose qu’on a un 2nd bâtiment avec 3 capteurs

1) Création aléatoirement la matrice représentant les températures mesurées par les 3 capteurs 
durant une journée 

In [49]:
#  la matrice aléatoire représentant les températures mesurées par les 3 capteurs 
#durant une journée 
np.random.seed(7)
matrice_batiment2 = np.random.uniform(15, 35, (3, 24))
print("Matrice du 2ᵉ bâtiment (3 capteurs x 24 heures) :")
print(matrice_batiment2)
print("Shape :", matrice_batiment2.shape)

Matrice du 2ᵉ bâtiment (3 capteurs x 24 heures) :
[[16.52616579 30.59837584 23.76818463 29.46930356 34.55979024 25.76991741
  25.02240927 16.44102267 20.3687796  24.99765002 28.58459992 31.07478072
  22.61882266 16.31872694 20.76291199 33.19187055 19.26770707 24.04247924
  33.62412039 15.49798455 27.01097835 34.00259001 19.60605758 25.96979838]
 [33.1825675  17.66338892 25.46825161 30.00819718 28.38026482 24.35505719
  19.09698181 24.81531778 22.44769379 24.5480231  22.31780772 31.75835989
  30.37295013 21.27989354 26.45250665 20.52098097 24.05685865 22.05956732
  28.14798926 22.40702166 24.18185956 29.38648245 23.25983658 33.12846538]
 [18.60903238 29.82237746 23.44748087 23.52907145 27.68759737 25.45812402
  23.29771957 15.02853761 16.84524692 29.18788787 25.48691194 28.92320927
  34.10936646 28.65827709 16.06257381 21.1770537  26.85189375 19.70240815
  34.29941999 33.90096448 31.96801762 24.44647993 31.8295343  17.62221285]]
Shape : (3, 24)


2) Déterminons de deux manières différentes la matrice qui fusionne les températures mesurées par 
les 8 capteurs durant une journée

In [ ]:
# Méthode 1 : np.concatenate le long de l'axe des lignes (axis=0)
matrice_fusionnee = np.concatenate([matrice_capteurs, matrice_batiment2], axis=0)
print("Matrice fusionnée (8 capteurs x 24 heures), shape :", matrice_fusionnee.shape)
 
# Méthode 2 : np.vstack pour empiler verticalement les matrices
matrice_fusionnee_vstack = np.vstack((matrice_capteurs, matrice_batiment2))
print("\nMatrice fusionnée avec vstack (8 capteurs x 24 heures), shape :", matrice_fusionnee_vstack.shape)
 
#verification que les deux méthodes donnent le même résultat    
print("\nLes deux méthodes donnent le même résultat :", np.array_equal(matrice_fusionnee, matrice_fusionnee_vstack))

Matrice fusionnée (8 capteurs x 24 heures), shape : (8, 24)

Matrice fusionnée avec vstack (8 capteurs x 24 heures), shape : (8, 24)

Les deux méthodes donnent le même résultat : True


## Partie 8 : Calcul scientifique

Considérons le tableau représentant les 24 températures du 1er bâtiment.

1) Pour les températures calculons le minimum, le maximum, la somme, la moyenne, la médiane, la 
variance et l’écart-type 

In [ ]:
 # Calcul du minimum en 24h
minimum_temp = np.min(matrice_capteurs)
print("Minimum des températures (24h) :", f"{minimum_temp:.2f}")

# Calcul du maximum en 24h
maximum_temp = np.max(matrice_capteurs)
print("Maximum des températures (24h) :", f"{maximum_temp:.2f}")

# Calcul de la somme en 24h
somme_temp = np.sum(matrice_capteurs)
print("Somme des températures (24h) :", f"{somme_temp:.2f}")

# Calcul de la moyenne en 24h
moyenne_temp = np.mean(matrice_capteurs)
print("Moyenne des températures (24h) :", f"{moyenne_temp:.2f}")

# Calcul de la médiane en 24h
mediane_temp = np.median(matrice_capteurs)
print("Médiane des températures (24h) :", f"{mediane_temp:.2f}")

# Calcul de la variance en 24h
variance_temp = np.var(matrice_capteurs)
print("Variance des températures (24h) :", f"{variance_temp:.2f}")

# Calcul de l’écart-type en 24h
ecart_type_temp = np.std(matrice_capteurs)
print("Écart-type des températures (24h) :", f"{ecart_type_temp:.2f}")

Minimum des températures (24h) : 15.11
Maximum des températures (24h) : 34.74
Somme des températures (24h) : 2945.06
Moyenne des températures (24h) : 24.54
Médiane des températures (24h) : 24.66
Variance des températures (24h) : 35.18
Écart-type des températures (24h) : 5.93


2) Standardisons le tableau des températures puis vérifier les valeurs de la moyenne et de l’écart
type du tableau standardisé 

In [80]:
# 2) Standardise le tableau des températures puis vérifier les valeurs de la moyenne et de l’écart-type du tableau standardisé 
temp_array_standardized = (matrice_capteurs - moyenne_temp) / ecart_type_temp
print("Tableau standardisé des températures :\n", temp_array_standardized)

# verification de la moyenne et de l’écart-type du tableau standardisé
 
print("Vérification -> moyenne :", abs(round(temp_array_standardized.mean(), 10)))
print("Vérification -> écart-type :", round(temp_array_standardized.std(), 10))

Tableau standardisé des températures :
 [[-0.34583728  1.59686122  0.85939721  0.40982727 -1.0826307  -1.08271202
  -1.41284027  1.31182214  0.41811     0.77874105 -1.53927683  1.66158324
   1.19808218 -0.8927338  -0.99561897 -0.99029319 -0.58286209  0.16065019
  -0.15228399 -0.62673864  0.45431514 -1.13834764 -0.6236518  -0.37341214]
 [-0.07094134  1.03871213 -0.93543775  0.12517296  0.38877453 -1.45206417
   0.43978963 -1.03372226 -1.38934618  1.59069512  1.64715963  1.11700817
  -0.58160941 -1.2793589   0.69836074 -0.12461067 -1.19720314  0.0609163
  -1.4927335   1.45729253 -0.73614815  0.62515818 -0.55767927  0.14484217]
 [ 0.23467243 -0.98540438  1.66048667  1.00484948  1.55904614  1.408426
   0.40726981  1.49962055 -1.31030998 -0.9478825  -1.4561882  -0.51175895
  -0.29817069 -0.69376882  1.18558951 -0.40580938 -0.66144926  0.22113768
  -1.13352485  1.09610226 -1.35731804  1.71882523  0.99511176 -0.9386682 ]
 [-1.59006296  1.14082627  0.77464362  0.84932664  0.99182628 -1.3590241

3) Normalisation (Min-Max) le tableau des températures puis vérifions les valeurs du tableau normalisé

In [81]:
# (Min-Max) le tableau des températures puis vérifier les valeurs du tableau normalisé
temp_array_normalized = (matrice_capteurs - minimum_temp) / (maximum_temp - minimum_temp)
print("Tableau normalisé des températures :\n", temp_array_normalized)

# Vérification des valeurs du tableau normalisé
print("Vérification -> minimum :", round(temp_array_normalized.min(), 10))
print("Vérification -> maximum :", round(temp_array_normalized.max(), 10))

Tableau normalisé des températures :
 [[0.3760253  0.96314049 0.74026683 0.60439946 0.15335431 0.15332973
  0.05355959 0.87699703 0.60690263 0.71589122 0.0153484  0.98270054
  0.84262295 0.21074425 0.17965067 0.18126021 0.30439254 0.52909408
  0.43452027 0.29113233 0.61784442 0.13651574 0.29206522 0.36769173]
 [0.45910334 0.79445873 0.19783842 0.51837228 0.59803698 0.04170548
  0.61345457 0.16813524 0.06065988 0.96127699 0.97834149 0.81812106
  0.30477112 0.09389984 0.69159898 0.44288359 0.11872865 0.49895287
  0.02941455 0.92096055 0.25806699 0.66947597 0.31200319 0.52431664]
 [0.55146481 0.18273769 0.98236914 0.78422488 0.95171215 0.90619229
  0.60362655 0.93375277 0.08454591 0.19407741 0.04045914 0.32588107
  0.39043092 0.27087471 0.83884747 0.35790075 0.28064221 0.54737439
  0.13797326 0.81180296 0.07033931 1.         0.78128198 0.19686213]
 [0.         0.82531929 0.71465291 0.73722334 0.78028906 0.06982371
  0.35964567 0.11244233 0.87386596 0.62950699 0.33155449 0.05913829
  0.311

4) Convertir le tableau initial en Fahrenheit 

In [82]:
# le tableau initial en Fahrenheit 
temp_array_fahrenheit = (matrice_capteurs * 9/5) + 32
print("Tableau des températures en Fahrenheit :\n", temp_array_fahrenheit)

Tableau des températures en Fahrenheit :
 [[72.48344428 93.22571503 85.35178191 80.55170543 64.61667106 64.61580273
  61.09101004 90.18234125 80.64014042 84.4906128  59.74104179 93.91675468
  88.96793507 66.64420798 65.54569882 65.60256235 69.95272075 77.89123154
  74.55002067 69.48424905 81.02670421 64.02177898 69.51720735 72.18902636]
 [75.41851943 87.26633461 66.18825616 77.51243978 80.32692448 60.67221486
  80.87161467 65.13886845 61.34185735 93.15987934 93.76275319 88.10230453
  69.96609569 62.5161961  83.63238895 74.84548977 63.39337645 76.82636876
  60.23798676 91.73553447 68.31607934 82.85080224 70.22159874 77.72244876]
 [78.68157006 65.6547604  93.9050466  86.90478164 92.8219619  91.21378462
  80.52439924 92.18747246 62.18573007 66.05538305 60.6281824  70.71189191
  72.99238243 68.76856514 88.83455033 71.84311976 69.11364235 78.53705899
  64.0732721  87.87909131 61.68382317 94.52792972 86.80081169 66.15376454]
 [59.19879622 88.35661142 84.44686438 85.24425805 86.76573248 61.66

## Partie 9 : Broadcasting

1)	Création aléatoirement la matrice temperatures_3x3 représentant les températures mesurées à 10h, 11h et 12h dans le 2nd bâtiment

In [87]:
# 1) Création aléatoire de la matrice temperatures_3x3
# représentant les températures mesurées à 10h, 11h et 12h dans le 2nd bâtiment
# lignes = heures (10h, 11h, 12h), colonnes = 3 capteurs du 2nd bâtiment

np.random.seed(42)
temperatures_3x3 = np.random.uniform(15, 35, (3, 3))
print("Températures (10h, 11h, 12h) - 2nd bâtiment :\n", temperatures_3x3)
print("shape :", temperatures_3x3.shape)

Températures (10h, 11h, 12h) - 2nd bâtiment :
 [[22.49080238 34.01428613 29.63987884]
 [26.97316968 18.12037281 18.11989041]
 [16.16167224 32.32352292 27.02230023]]
shape : (3, 3)


2)	Supposons que les valeurs de calibration des capteurs soient stockées dans le tableau 
correction = np.array([1, -0.5, 0.2])
- Appliquons automatiquement les corrections pour trouver les mesures corrigées
     mesures_corrigees = temperatures_3x3 + correction


In [89]:
# 2) Application des corrections de calibration par capteur
correction = np.array([1, -0.5, 0.2])
mesures_corrigees = temperatures_3x3 + correction

print("\nCorrections appliquées :", correction)
print("\nMesures corrigées :\n", mesures_corrigees)


Corrections appliquées : [ 1.  -0.5  0.2]

Mesures corrigées :
 [[23.49080238 33.51428613 29.83987884]
 [27.97316968 17.62037281 18.31989041]
 [17.16167224 31.82352292 27.22230023]]
