**Atelier Numpy**

Partie 1 : Listes Python vs tableaux NumPy

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0, 25.8

1) Créeation d'une liste Python stockant ces températures

In [3]:
temp_list = [24.5, 25.1, 26.3, 27.0, 25.8]
print("Températures enregistrées :", temp_list)

Températures enregistrées : [24.5, 25.1, 26.3, 27.0, 25.8]


2) Création d'un tableau NumPy équivalent stockant ces températures

In [4]:
# importation de la bibliothèque NumPy
import numpy as np

#tableau de températures sous forme de tableau NumPy
temp_array = np.array(temp_list)
print("Tableau NumPy des températures :", temp_array)


Tableau NumPy des températures : [24.5 25.1 26.3 27.  25.8]


3) Une multiplication par 2 sur ces deux collections

In [5]:
# multiplication par 2 sur ces deux collections de données
 
# multiplication par 2 sur la liste
result_list = temp_list * 2
print("Résultat de la multiplication par 2 sur la liste :", result_list)

# multiplication par 2 sur le tableau NumPy
result_array = temp_array * 2   
print("Résultat de la multiplication par 2 sur le tableau NumPy :", result_array)

Résultat de la multiplication par 2 sur la liste : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Résultat de la multiplication par 2 sur le tableau NumPy : [49.  50.2 52.6 54.  51.6]


4) La difference qu'on a observe 

- Sur la liste Python, l'opérateur * réalise une répétition : la liste est dupliquée et concaténée deux fois (elle passe de 5 à 10 éléments), ce qui n'a aucun sens mathématique pour des mesures physiques.
- Sur le tableau NumPy, l'opérateur * réalise une multiplication élément par élément (opération vectorisée) : chaque température est bien multipliée par 2, et la taille du tableau reste inchangée (5 éléments).
- Cette différence illustre l'intérêt majeur de NumPy pour le calcul scientifique : les opérations sont vectorisées, plus rapides et sémantiquement correctes pour des données numériques.

Partie 2 – Création des données

1) Création d'un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [8]:
# les mesures de temperature de 10 capteurs initie a 0 
capture_zero = np.zeros(10)
print("Mesures de température des 10 capteurs :", capture_zero)

Mesures de température des 10 capteurs : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Création d'un tableau contenant 10 valeurs égales à 1. 

In [9]:
#Tableau contenant 10 valeur egal a 1 
capture_one = np.ones(10)
print("Mesures de température des 10 capteurs :", capture_one)

Mesures de température des 10 capteurs : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3) Création d'un tableau de 10 valeurs initialisées à 25.

In [10]:
# Tableau 10 valeur initialise a 25 
capture_25 = np.full(10, 25)
print("Mesures de température des 10 capteurs :", capture_25)

Mesures de température des 10 capteurs : [25 25 25 25 25 25 25 25 25 25]


4) Création d'une matrice identité de taille 5 × 5. 

In [11]:
#Matrice 5*5
identite = np.eye(5)
print("Matrice identité 5x5 :\n", identite)

Matrice identité 5x5 :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5) Création des 24 heures (de 0 à 23) de mesure d’une journée

In [12]:
# Les 24h de mesure d'une journée*
heures = np.arange(24)
print("Heures de la journée :", heures)

Heures de la journée : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6) Création des 10 valeurs régulièrement réparties entre 20 °C et 30 °C  

In [13]:
#  10 valeurs régulièrement réparties entre 20 °C et 30 °C  
capture_20_30 = np.linspace(20, 30, 10)
print("Mesures de température des 10 capteurs :", capture_20_30)

Mesures de température des 10 capteurs : [20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7) Création aléatoir des températures de 100 mesures, en rendant les résultats reproductibles

In [14]:
# les températures de 100 mesures, en rendant les résultats reproductibles
np.random.seed(42)
capture_100 = np.random.uniform(20, 30, 100)
print("Mesures de température des 100 capteurs :", capture_100)

Mesures de température des 100 capteurs : [23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682
 20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
 23.58465729

Partie 3 – Exploration des tableaux

1) Création d'un tableau aléatoire qui représente les 24 températures d'une journée 

In [16]:
# Tableau aléatoire qui représente les 24 températures d'une journée
np.random.seed(42)
capture_24 = np.random.uniform(15, 35, 24)
print("Mesures de température des 24 capteurs :", capture_24)

Mesures de température des 24 capteurs : [22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687]


2) Détermination des propriétés suivantes du tableau 

a) nombre de dimensions

In [17]:
# nombre de dimensions du tableau
print("Nombre de dimensions du tableau capture_24 :", capture_24.ndim)

Nombre de dimensions du tableau capture_24 : 1


b) nombre de valeurs

In [18]:
# nombre de valeurs dans le tableau
print("Nombre de valeurs dans le tableau capture_24 :", capture_24.size)

Nombre de valeurs dans le tableau capture_24 : 24


c) type des données

In [19]:
# type de données du tableau
print("Type de données du tableau capture_24 :", capture_24.dtype)

Type de données du tableau capture_24 : float64


d) forme du tableau

In [20]:
# format du tableau
print("Format du tableau capture_24 :", capture_24.shape)

Format du tableau capture_24 : (24,)
